# Ruby cops
Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/Send:
  Enabled: true

# Additional Configurations
Layout/EndOfLine:
  EnforcedStyle: lf

Layout/LineLength:
  Max: 120

Layout/HashAlignment:
  EnforcedColonStyle: table

Metrics/AbcSize:
  Max: 30

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/ClassLength:
  Max: 120
  Exclude:
    - 'app/models/**/*.rb'

# RSpec
RSpec/NestedGroups:
  Max: 4
